sudo: required
language: bash
services:
  - docker

before_script:
  - docker build . --tag=$APP_IMAGE --tag=$APP_IMAGE:dev
script:
  - make test
after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true

  script: ./deploy.sh
  on:
    tags: true

branches:
  only:
    - master
    - /\d+\.\d+\.\d+/
